# Generated by Django 4.0.10 on 2023-08-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20211203_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitpolluser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
